# -*- coding: utf-8 -*-
"""SML-A1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1r9hZhJ5yivod-DmlX-f0ERGQZkbAAC1j
"""

#importing libraries
import matplotlib.pyplot as plt
import numpy as np
import math

"""#Q1"""

x = np.arange(-10,10,0.01)
pw1 = ((2*math.pi)**-0.5) * np.exp(-0.5 * (x-2)**2)
plt.plot(x , pw1)
plt.title("P(x|w1) vs x")

pw2 = ((2*math.pi)**-0.5) * np.exp(-0.5 * (x-5)**2)
plt.plot(x , pw2)
plt.title("P(x|w2) vs x")

y = pw1/pw2
plt.plot(x,y)
plt.title("P(x|w1)/P(x|w2) vs x")

"""#Q3b"""

def plotting(a1,a2,b):
    x = np.arange(-10, 10, 0.02)
    pw1 = ((math.pi * b)*-1) * (1 + ((x - a1)/b)**2 )**-1
    pw2 = ((math.pi * b)*-1) * (1 + ((x - a2)/b)**2 )**-1
    pw1x = (pw1 * 0.5)/(pw1 + pw2)
    plt.title("p(w1|x) for a1 = 3, a2= 5 and b= 1")
    plt.plot(x,pw1x)
    plt.show()

plotting(3,5,1)